// import {ReactComponent as SQUAREICON }from './square.svg';
// import {ReactComponent as CIRCLEICON} from './circle.svg';
// import {ReactComponent as HEARTICON} from './heart.svg';
// import {ReactComponent as TRIANGLEICON} from './triangle.svg';
// import {ReactComponent as STARICON} from './star.svg';
// import {ReactComponent as LINEICON} from './substract.svg';
const SQUAREICON = 'square.svg';
const CIRCLEICON = 'circle.svg';
const HEARTICON = 'heart.svg';
const TRIANGLEICON = 'triangle.svg';
const STARICON = 'star.svg';
const LINEICON = 'substract.svg';
export {SQUAREICON, CIRCLEICON, HEARTICON, TRIANGLEICON, STARICON, LINEICON};